### ISSUE TITLE
Cannot swipe on mobile Safari (iPad2)

### ISSUE THREAD

**Issue by redaxmedia** [wilsonfletcher/Optiscroll#11]
Hello,

there is a strange issue on mobile Safari. I cannot "swipe" the scrollable container by default, but after using one of the tracks the container can be scrolled using touch gestures.

It seems like something goes wrong with preventParentScroll, it maby is focusing the wrong container?

Best regards

**Comment by albertogasparin** [comment]
Can you provide an example of this behavior? So I can debug it more easily. 
However, I think that the problem is related to `preventParentScroll` with a non scrollable container.
Try adding the [CSS tweaks](https://github.com/wilsonfletcher/Optiscroll/blob/master/scss/optiscroll.scss#L77) for forcing the scrollbars and it should work as expected.

**Comment by redaxmedia** [comment]
I tried the tweaks but did not found a <code>optiscroll-prevent</code> class. Do I have to add it manually?

**Comment by albertogasparin** [comment]
No, the class is [added automatically](https://github.com/wilsonfletcher/Optiscroll/blob/master/src/optiscroll.js#L83) if the device is touch and `preventParentScroll` is `true`.

**Comment by redaxmedia** [comment]
I will check this out tomorrow, thanks.

**Comment by redaxmedia** [comment]
There is a naming issue in your dist files because the tweak is called <code>optiscroll-nobounce</code> and not <code>optiscroll-nobounce</code>.

However it does not help to focus the right element. I can scroll another element 1px to 2px one time, maby this is the parent element?

**Comment by redaxmedia** [comment]
Just fixed it, the trick was to prevent event bubbling on the content element.

<pre>
var contentElement = $('.pf-scrollbar-content');

contentElement.on('touchstart touchmove touchend', function (event) {
    event.stopPropagation();
});
</pre>
