### ISSUE TITLE
Container

### ISSUE THREAD

**Issue by brunowego** [wilsonfletcher/Optiscroll#13]
I believe the container "optiscroll-content" could be added dynamically:

```html
<div id="scroll" class="optiscroll">
    <div class="optiscroll-content">
        <!-- this is the area that actually scrolls -->
        My content
    </div>
    <!-- scrollbars elements will be added here  -->
</div>
```

This propose is for easy use of optiscroll:

```html
<div id="scroll" class="optiscroll">
    My content
</div>
```

**Comment by albertogasparin** [comment]
Thanks @brunowego, I have not implemented this in first instance because I was worried about the "flash" of unwrapped content. But probably it is something worth trying to implement as the `optiscroll` container now has `overflow: hidden`.

**Comment by brunowego** [comment]
Thank you @albertogasparin for this great project. I appreciate your feedback, what you think about this issue, close or wait for this changes?

**Comment by albertogasparin** [comment]
Leave it open, I will make it for v1.1 :wink:

**Comment by brunowego** [comment]
Hi @albertogasparin, have any idea when you will publish the 1.1 release? Thanks!
