### ISSUE TITLE
Severe lag with FireFox 40

### ISSUE THREAD

**Issue by Aedaeum** [wilsonfletcher/Optiscroll#15]
I'm not sure how I should represent my specific use-case, but I'm writing a chat application which adds elements dynamically to a container with a message-tray element. The container is instantiated as the scroll object with Optiscroll.

For some reason (only in FireFox) after I add about 10 messages, the entire screen starts flickering like it's trying to re-render the objects in the container... It's very strange. Here's some of my code.

```javascript
// Initialization
this._scrollObj = new Optiscroll(this._oPort, {
  autoUpdate: false
 });


scrollPort() {
  // The timeout is arbitrary to wait until the object is rendered to the 
  // container before the update happens.
  setTimeout(() => {
    this._scrollObj.update();
    this._scrollObj.scrollTo(false, 'bottom', 300);
  }, 50);
}
```

The above `scrollPort` method is only executed when a message is added to the `message-tray`. I should also mention that this bug still exists even without the execution of the `scrollPort` method. Just having the `Optiscroll` instantiated, is enough to cause it to glitch out.

**edit** I should add that I removed all transitions from the inner elements and still no luck. I'm also using the vanilla JavaScript version, NOT jQuery.

**Comment by albertogasparin** [comment]
First of all, one thing that might cause the issue is that you are calling `update()` right before `scrollTo()`. That call should be removed as `scrollTo` [does it by itself](https://github.com/wilsonfletcher/Optiscroll/blob/master/src/optiscroll.js#L183).
Then, if that does not help, would you mind creating an online jsbin (or anything else) in order to let better debug the issue? As the Optiscroll demo website works fine in FF40.

**Comment by Aedaeum** [comment]
Well I disabled the calling of that function and it still glitches out for me. It's really hard to do a jsbin since there's a lot of functionality that is implemented.

I do have a keyhandler that goes off on every key-stroke, which I'm going to test if there's some weird sort of connection there.

**Comment by albertogasparin** [comment]
Well, I cannot think of anything else that might cause that issue, as setting `autoUpdate: false` disables the polling and Optiscroll should be "paused", only listening for scroll events.

**Comment by Aedaeum** [comment]
It's very strange... I tried another scrollbar plugin `perfect-scrollbar` and it has the exact same lag. It's not graphic lag, it causes lag in my contenteditable div, while typing.

**Comment by Aedaeum** [comment]
The only thing I can think of is that it has to do with my custom element. I'm using the Aurelia framework which creates and populates custom elements onto the page. Have you tested your scrollbar with custom elements?

**Comment by Aedaeum** [comment]
Okay, I've broken it down to the simplest I could. I setup an interval and removed all key events from the element. The interval simply adds an element every `500ms`. After a while when I type in the contenteditable div, it becomes extremely laggy and the scroll container starts to appear to redraw with every key stroke...

**Comment by Aedaeum** [comment]
Turns out it's a flex-box bug: https://bugzilla.mozilla.org/show_bug.cgi?id=946167

I'm not sure if you can somehow get around it...

**Comment by albertogasparin** [comment]
Wow, that's a really nasty bug. The ticket says that it has been fixed but apparently it is not. 
Have you tried adding a translate3d transformation? Maybe by hardware accelerating the container the reflow becomes faster. 
Apart from that, I cannot think of a way to avoid the reflow as Optiscroll needs to update it's internal cache.

**Comment by Aedaeum** [comment]
What kind of transformation would you suggest? I'm not too familiar with those as of yet.

And yeah, it's quite annoying. The sad part is, using `-moz-box` (the old spec) has no performance hit at all, but it also doesn't order the flex boxes correctly.

**Comment by Aedaeum** [comment]
Ugh, looks like I"m going to have to write styles JUST for FireFox... It's really dissapointing to encounter such a horrible oversight in design, especially when all other browsers are displaying nested flex boxes perfectly.

I actually went through and slowly disabled the nested flex items, which gradually increased the performance, but sadly it wasn't enough, which is why I'm going to have to write a large section of layout code JUST for FireFox.

**Comment by albertogasparin** [comment]
Agree, really disappointing. Flexbox have been around for a while and still
there are issues and performance drawbacks. You should file a bug in
Firefox so maybe someone can look at it.

On 8 Sep 2015 10:29 am, "Aedaeum" <notifications@github.com> wrote:
>
> Ugh, looks like I"m going to have to write styles JUST for FireFox...
It's really dissapointing to encounter such a horrible oversight in design,
especially when all other browsers are displaying nested flex boxes
perfectly.
>
> I actually went through and slowly disabled the nested flex items, which
gradually increased the performance, but sadly it wasn't enough, which is
why I'm going to have to write a large section of layout code JUST for
FireFox.
