### ISSUE TITLE
direction

### ISSUE THREAD

**Issue by puppetMaster3** [wilsonfletcher/Optiscroll#17]
do you indicate direction of scroll? up/down?

So if I go down - I can go to next div or such

**Comment by albertogasparin** [comment]
No, direction is not part of the event `detail` object. However it is fairly easy to get. Just cache previous value and compare it with the one passed to the event. 
Something like (untested):

```js
var optiscrollEl = document.querySelector('#scroll'),
    percentage = 0;

optiscrollEl.addEventListener('scroll', function (ev) {
  var newPercentage = ev.detail.scrollbarV.percent;
  if(newPercentage > percentage) {
    // direction down
  } else {
    // direction up
  }
  percentage = newPercentage;
});
