### ISSUE TITLE
Optiscroll doesn't disable native scrollbars on Firefox on Mac

### ISSUE THREAD

**Issue by stereokai** [wilsonfletcher/Optiscroll#19]
The problem happens when scrollbars are hidden by default, and shown only while scrolling:
<img width="424" alt="screen shot 2016-01-20 at 13 44 06" src="https://cloud.githubusercontent.com/assets/2685357/12448013/fa4b41e2-bf7b-11e5-9d99-7871df3c7c11.png">

It's weird because it takes place *only* on Firefox, but I could see in your website that it's perfectly fine, regardless of OS setting.

**Comment by albertogasparin** [comment]
Thanks for pointing this out. I saw that an error is thrown on FF Mac when only trackpad is used.
However the custom scrollbar will not be enabled on FF Mac (on trackpad) anyway, as there is no way to hide the browser one: see https://bugzilla.mozilla.org/show_bug.cgi?id=926294.

I've pushed a new version with the fix and updated the readme with the relevant information.

**Comment by stereokai** [comment]
Here's the odd thing - it did hide the native scrollbars on the Optiscroll demo page though

**Comment by albertogasparin** [comment]
If you plug the mouse, then the plugin will still "work" because the offset right will persist. However, together with the scrollbar we are also loosing 16px of content that is now clipped.

**Comment by stereokai** [comment]
Again, I don't understand why the emphasis on connecting a mouse - it already worked on your website, before your fix - with or without a mouse attached

**Comment by albertogasparin** [comment]
It was not really working. It was wrongly clipping 16px of content out of the view. The expected behaviour on Firefox Mac is:
- with mouse attached Optiscroll works as expected and hides the scrollbars
- with trackpad only, Optiscroll keeps the native scrollabars as we cannot hide them with CSS

**Comment by stereokai** [comment]
Are you using an Apple mouse? Because I'm using a Microsoft mouse (the drivers are different) and the result is the same - Native hidden scrollbars appear while scrolling, alongside Optiscroll's scrollbars (I of course used `forceScrollbars: true`.

**Comment by stereokai** [comment]
Sorry, silly mistake - I didn't refresh Firefox after enabling native hidden scrollbars - that's why it was working for me. After refreshing - It doesn't work.
