### ISSUE TITLE
NPM package?

### ISSUE THREAD

**Issue by jonataswalker** [wilsonfletcher/Optiscroll#22]
Hi there,

I'd like to use this as a dependency in https://github.com/jonataswalker/ol3-contextmenu but this is not an NPM package.

May you publish it?

Great work. Thank you.

**Comment by albertogasparin** [comment]
Done. https://www.npmjs.com/package/optiscroll

**Comment by Sinled** [comment]
Hi, thanks for publishing this addon
is it possible to publish 1.0.6 version to npm?
Currently i have problems with 2+ version in my application

**Comment by albertogasparin** [comment]
Sorry to hear that. I've tried to look for a way to publish all versions to npm, but it looks like it is no longer possible and unfortunately `npm publish --tag v1.0.6` fails as my tag names are SemVer (odd but true). 
Anyway, you can explicitly specify the Github tag: 
```
npm i --save github:wilsonfletcher/Optiscroll#v1.0.6
```

It's less pretty but as I'm no longer supporting v1.x there is no practical difference.
