### ISSUE TITLE
Question about scrollIntoView()

### ISSUE THREAD

**Issue by redaxmedia** [wilsonfletcher/Optiscroll#6]
Why don't you use the native Element.scrollIntoView()

https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

**Comment by albertogasparin** [comment]
Optiscroll `scrollIntoView` implementation adds behaviours that are missing in the native implementation. For instance, the native  `scrollIntoView` does not allow you to animate the scrolling (same limitation applies for the native `scrollTo`).

As you are pointing out, now finally something has started to change. There is a [working draft specification](http://dev.w3.org/csswg/cssom-view/#dictdef-scrollintoviewoptions) for `scrollIntoViewOptions` argument and it has been implemented in Firefox 36.

It is a good starting point and, eventually, we will align `scrollIntoView` method with the new specification (and using the native implementation if feature detection will be possible).

**Comment by redaxmedia** [comment]
Okay, thank you for pointing this out.
